<?php

namespace common\models;

use Yii;
use yii\db\Expression;

/**
 * This is the model class for table "wallet".
 *
 * @property int $id
 * @property int $visit_id
 * @property string $datetime
 * @property string $type
 * @property string $addr
 * @property int $amount
 *
 * @property Visit $visit
 */
class Wallet extends \yii\db\ActiveRecord
{
    public $utm_source;
    public $amount_of_sessions;
    public $last_visit;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'wallet';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['visit_id'], 'integer'],
            [['amount'], 'string'],
            [['datetime'], 'safe'],
            [['type'], 'string', 'max' => 7],
            [['addr'], 'string', 'max' => 42],
            [['visit_id'], 'exist', 'skipOnError' => true, 'targetClass' => Visit::className(), 'targetAttribute' => ['visit_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'visit_id' => 'Visit ID',
            'datetime' => 'Datetime',
            'type' => 'Type',
            'addr' => 'Addr',
            'amount' => 'Amount (ETH)',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVisit()
    {
        return $this->hasOne(Visit::className(), ['id' => 'visit_id']);
    }

    public static function getMostReachWallets()
    {
        return self::find()
            ->select(['wallet.addr as addr', 'wallet.amount as amount', 'utm_source', 'count(visit.session) as amount_of_sessions', 'MAX(visit.datetime) as last_visit'])
            ->joinWith('visit')
            ->groupBy('wallet.addr')
            ->orderBy('amount DESC');
    }

    public function beforeSave($insert)
    {
        $this->datetime = new Expression('NOW()');
        $this->type = 'ETH';
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
